# -*- coding: utf-8 -*-
"""ProjetoAnáliseDeDados_LeagueOfLegends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1XIQvQG3ThJIFj4TPc8x7HS1fo25WTH

# 🎮 Análise de Dados de um Dataset da plataforma Kaggle sobre League of Legends


---
<br>

### 🌲 O dataset conta com informações voltadas para a rota ***Jungle*** no servidor Europeu 2026 e possui as seguintes colunas:
* Ranque
* Campeão
* Vitória (1 para Sim e 0 para Não)
* Kills
* Mortes
* Assistências
* KDA
* Participação em Kills (KP)
* Farm
* Farm por Minuto
* Ouro
* Dano
* % Dano
* Dano sofrido
* Visão
* Wards
* Wards Destruídas
* Wards de Controle
* Dragões
* Barons
* Arautos
* Torres
* Participação em Dragões
* Participação em Barons
* Participação em Torres
* Runa
* Duração da Partida
* ID da Partida
<br>


---

<br>

### 💡 Aqui as questões que busco responder:
* Análise das métricas por ranque;
* Correlação de objetivos com vitória;
* Importância de um bom KDA;
* Importância de farm e ouro;
* Diferença do uso de visão por ranque;
* Existência de uma runa mais favorável;
* Relação do ouro com o dano;
* Futuras questões que possam aparecer.
"""

# Importando as bibliotecas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importando os dados

df = pd.read_csv('/content/lol-jungler-ranked-euw-2026.csv')

# Renomeando as colunas

df.rename(columns={
    'rank': 'Ranque',
    'champion': 'Campeão',
    'win': 'Vitória',
    'kills': 'Kills',
    'deaths': 'Mortes',
    'assists': 'Assistências',
    'kp': 'Participações',
    'cs': 'Farm',
    'cspm': 'Farm por Minuto',
    'gold': 'Ouro',
    'dmg': 'Dano',
    'dmgshare': '% Dano',
    'dmgtaken': 'Dano sofrido',
    'vision': 'Visão',
    'wards': 'Wards',
    'wardskilled': 'Wards Destruídas',
    'cwards': 'Wards de Controle',
    'teamdragons': 'Dragões',
    'teambarons': 'Barons',
    'teamheralds': 'Arautos',
    'teamtowers': 'Torres',
    'pdrag': 'Participação em Dragões',
    'pbaron': 'Participação em Barons',
    'pturret': 'Participação em Torres',
    'keystone': 'Runa',
    'dur': 'Duração da Partida',
    'matchId': 'ID da Partida'
}, inplace=True)

# Criando a coluna KDA e colocando na quarta posição (índice 3)

df.insert(
    3,
    "KDA",
    np.where(
        df["Mortes"] == 0,
        df["Kills"] + df["Assistências"],
        (df["Kills"] + df["Assistências"]) / df["Mortes"]
    )
)

# Deletando a linha onde Ranque = Master (1 único registro)
df = df[df["Ranque"] != "MASTER"]

# Padronizando os campos de ["Vitória"]

df["Vitória_num"] = df["Vitória"].map({
    "1": 1,
    "0": 0,
    "true": 1,
    "false": 0
})

df.info()

"""## ⚡ Análise de métricas por ranque"""

# Quantidade de jogadores por ranque

df['Ranque'].value_counts()

# Média dos objetivos e métricas por ranque

df.groupby("Ranque")[["Dragões", "Barons", "Arautos", "Torres", "Wards", "Wards de Controle", "Duração da Partida"]].mean().round(2)

"""## 🗼 Correlação de objetivos com vitória"""

# As métricas quando o jogador vence

df[df["Vitória_num"] == 1].groupby("Ranque")[["Dragões", "Barons", "Arautos", "Torres", "Wards", "Wards de Controle", "Duração da Partida"]].mean().round(2)

# As métricas quando o jogador perde

df[df["Vitória_num"] == 0].groupby("Ranque")[["Dragões", "Barons", "Arautos", "Torres", "Wards", "Wards de Controle", "Duração da Partida"]].mean().round(2)

"""## ⛔ Importância de um bom KDA"""

# Média de KDA nas vitórias

df[df["Vitória_num"] == 1].groupby("Ranque")[["KDA"]].mean().round(2)

# Média de KDA nas derrotas

df[df["Vitória_num"] == 0].groupby("Ranque")[["KDA"]].mean().round(2)

"""## 🥇 Importância de farm e ouro"""

# Média de farm nas vitórias

df[df["Vitória_num"] == 1].groupby("Ranque")[["Farm"]].mean().round(2)

# Média de farm nas derrotas

df[df["Vitória_num"] == 0].groupby("Ranque")[["Farm"]].mean().round(2)

# Média de ouro nas vitórias

df[df["Vitória_num"] == 1].groupby("Ranque")[["Ouro"]].mean().round(2)

# Média de ouro nas derrotas

df[df["Vitória_num"] == 0].groupby("Ranque")[["Ouro"]].mean().round(2)

"""## 👀 Diferença do uso de visão por ranque"""

# Média de visão

df.groupby("Ranque")[["Visão", "Wards", "Wards Destruídas", "Wards de Controle"]].mean().round(2)

# Média de visão nas vitórias

df[df["Vitória_num"] == 1].groupby("Ranque")[["Visão", "Wards", "Wards Destruídas", "Wards de Controle"]].mean().round(2)

# Média de visão nas derrotas

df[df["Vitória_num"] == 0].groupby("Ranque")[["Visão", "Wards", "Wards Destruídas", "Wards de Controle"]].mean().round(2)

"""## 🌴 Campeão com mais vitórias e derrotas"""

# Campeões com mais vitórias

df[df["Vitória_num"] == 1]["Campeão"].value_counts().head()

# Taxa de vitória por elo (10 ou mais jogos)

resultado = (
    df.groupby(["Ranque", "Campeão"])
      .agg(
          Jogos=("Vitória_num", "count"),
          Taxa_Vitoria=("Vitória_num", "mean")
      )
      .query("Jogos > 9")
)

resultado["Taxa_Vitoria"] = (resultado["Taxa_Vitoria"] * 100).round(2)

resultado.reset_index().groupby("Ranque").head(1)

# Campeões com mais derrotas

df[df["Vitória_num"] == 0]["Campeão"].value_counts().head()

"""## 🧿 Runas escolhidas"""

# Runas escolhidas

df['Runa'].value_counts()

# Campeões que mais utilizaram a runa Conqueror

df[df["Runa"] == "Conqueror"]["Campeão"].value_counts().head(10)

# Kayn sendo o campeão que mais venceu, quais runas foram escolhidas nas vitórias

df[(df["Campeão"] == "Kayn") & (df["Vitória"] == "1")]["Runa"].value_counts()

"""## ☯ Correlações"""

# Correlação entre ouro e dano

df["Dano"].corr(df["Ouro"])

# Correlações entre diversas métricas e a vitória

df.groupby("Ranque").apply(
    lambda grupo: grupo[["Vitória_num","KDA", "Dano", "Farm", "Ouro", "Dragões", "Barons", "Arautos", "Visão"]]
    .corr()["Vitória_num"]
)

"""# 📊 GRÁFICOS

"""

# Correlação Ouro x Dano

df.plot.scatter(x="Ouro", y="Dano")

# Média de Dragões, Barões e Arautos nas vitórias(1) e derrotas(0)

df.groupby("Vitória_num")[["Dragões", "Barons", "Arautos"]].mean().plot.bar(
    title="Objetivos por resultado",
    ylabel="Média",
    xlabel='Nas Derrotas // Nas Vitórias'
)

# Correlações de objetivos e métricas com Vitória

correlacoes = (
    df[[
        "Vitória_num",
        "Ouro",
        "Dano",
        "Dragões",
        "Barons",
        "Arautos",
        "KDA"
    ]]
    .corr()["Vitória_num"]
    .drop("Vitória_num")
    .sort_values()
)

correlacoes.plot.barh(
    title="Correlação com Vitória",
    xlabel="Correlação"
)

# Os 5 campeões mais escolhidos

df["Campeão"].value_counts().head(5).plot.pie(
    autopct="%.1f%%",
    title="Top 10 Campeões mais escolhidos"
)

"""# 📚 Relatório Final

### ⭐ Foram analisados 1625 jogos, dividos por ranque da seguinte forma:
* BRONZE   |	285


---


* SILVER (PRATA)  |	255


---


* IRON (FERRO)    |	251


---


* GOLD (OURO)    |	238


---


* DIAMOND (DIAMANTE) |	203


---


* EMERALD (ESMERALDA) |	200


---


* PLATINUM (PLATINA) |	193

### ⭐ O campeão que mais venceu partidas absolutas foi **Kayn**. Na divisão por elo, os campeões com pelo menos 10 jogos com maior taxa de vitória foram:

|index|Ranque|Campeão|Jogos|Taxa\_Vitoria|
|---|---|---|---|---|
|0|BRONZE|Briar|11|72\.73|
|10|DIAMOND|Briar|10|50\.0|
|17|EMERALD|Graves|16|31\.25|
|22|GOLD|Hecarim|11|36\.36|
|27|IRON|Aatrox|14|35\.71|
|36|PLATINUM|Lee Sin|49|38\.78|
|38|SILVER|Diana|12|58\.33|

* Briar é um campeão com alta taxa de vitória no Bronze e também tem a maior taxa no Diamante, mas aparece relativamente pouco nas partidas;
* Lee Sin aparece em muitos jogos no Platina e tem a maior taxa de vitória, mesmo assim a taxa é bastante baixa.

### ⭐ As médias de objetivos por elo nas vitórias:

|Ranque|Dragões|Barons|Arautos|Torres|Wards|Wards de Controle|Duração da Partida|
|---|---|---|---|---|---|---|---|
|BRONZE|2\.72|0\.65|0\.62|8\.24|7\.37|0\.83|889\.39|
|DIAMOND|2\.62|0\.85|0\.41|8\.51|5\.15|1\.53|376\.49|
|EMERALD|2\.79|0\.81|0\.51|8\.81|6\.38|1\.4|407\.53|
|GOLD|2\.85|0\.9|0\.52|8\.98|7\.82|1\.58|741\.79|
|IRON|2\.62|0\.57|0\.5|8\.55|6\.94|1\.17|877\.53|
|PLATINUM|3\.08|0\.93|0\.55|8\.71|7\.1|1\.53|849\.6|
|SILVER|2\.9|0\.76|0\.49|8\.97|7\.58|0\.61|382\.3|

* Podemos notar que o elo Platina é o que mais realiza dragões e barões;
* Os arautos aparecem com mais relevância no elo Bronze;
* Torres são altamente contestadas em todos os elos, sem diferenças significativas;
* As partidas tendem a durar mais nos elos Bronze, Ferro e Platina;
* Já, nos elos Diamante, Prata e Esmeralda, as partidas costumam ser mais rápidas.

### ⭐ As médias de objetivos por elo nas derrotas:
|Ranque|Dragões|Barons|Arautos|Torres|Wards|Wards de Controle|Duração da Partida|
|---|---|---|---|---|---|---|---|
|BRONZE|1\.43|0\.15|0\.33|3\.04|8\.04|0\.97|829\.1|
|DIAMOND|1\.42|0\.25|0\.26|3\.53|6\.14|1\.41|336\.21|
|EMERALD|1\.38|0\.19|0\.23|3\.44|6\.31|1\.68|473\.31|
|GOLD|1\.26|0\.21|0\.27|3\.44|7\.3|1\.13|893\.51|
|IRON|1\.04|0\.19|0\.26|2\.85|5\.85|0\.64|917\.55|
|PLATINUM|1\.26|0\.16|0\.23|3\.08|8\.34|1\.74|707\.58|
|SILVER|1\.33|0\.16|0\.32|3\.21|6\.85|0\.5|389\.41|

* Em relação à tabela das vitórias, nota-se pouca ou nenhum diferença nos quesitos Wards e Wards de Controle;
* O elo que menos realiza dragões nas derrotas é o Ferro, seguido por Ouro e Platina;
* Barões e Arautos quase nunca são contestados nas derrotas;
* Agora nas derrotas, os elos que mais demoram a terminar as partidas são Ferro, Ouro e Bronze;
* Os elos que perdem em partidas mais rápidas são Diamante, Prata e Esmeralda.

### ⭐ Os gráficos de Média de Dragões, Barões e Arautos nas vitórias(1) e derrotas(0) e suas correlações demonstram a relevância desses objetivos na conquista da partida:
* Realizar dragões mostra a maior correlação com a vitória entre todas as métricas estudadas;
* KDA e Barões também possuem correlações fortes com a vitória;
* A menor correlação é com dano.
"""